language = "C"

[export]
include = [
    "ID3D11ShaderReflection",
    "ID3D11ShaderReflectionVtbl",
    "ID3D11ShaderReflectionConstantBuffer",
    "ID3D11ShaderReflectionConstantBufferVtbl",
    "ID3D11ShaderReflectionVariable",
    "ID3D11ShaderReflectionVariableVtbl",
    "ID3D11ShaderReflectionType",
    "ID3D11ShaderReflectionTypeVtbl",
    "D3D11_SHADER_DESC",
    "D3D11_SHADER_BUFFER_DESC",
    "D3D11_SHADER_INPUT_BIND_DESC",
    "D3D11_SIGNATURE_PARAMETER_DESC",
    "D3D11_SHADER_VARIABLE_DESC",
    "D3D11_SHADER_TYPE_DESC",
]

[parse]
parse_deps = false

[export.rename]
# Ensure proper pointer types are used
