[package]
name = "d3dcrs"
description = "Safe, ergonomic Rust API for D3DCompiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
d3dcompiler = { path = "../d3dcompiler" }
thiserror = "2"
bitflags = "2"

[dev-dependencies]
pretty_assertions = "1"
